# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_end_price', models.FloatField()),
                ('fundamental_value', models.FloatField()),
                ('latent_demand_value', models.FloatField()),
                ('ticker', models.CharField(max_length=10))
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='AssetInvestors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocks_owned', models.FloatField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtime_demand.Asset')),
            ],
            options={
                'verbose_name': 'AssetInvestors',
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aum', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Investor',
                'verbose_name_plural': 'Investors',
            },
        ),
        migrations.AddField(
            model_name='assetinvestors',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtime_demand.Investor'),
        ),
        migrations.AlterModelOptions(
            name='assetinvestors',
            options={'verbose_name': 'AssetInvestors', 'verbose_name_plural': 'AssetInvestors'},
        )
    ]
