# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_demand', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='quarter_end_price',
        ),
        migrations.RemoveField(
            model_name='assetinvestors',
            name='stocks_owned',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='aum',
        ),
        migrations.AddField(
            model_name='asset',
            name='current_market_cap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AddField(
            model_name='asset',
            name='household_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AddField(
            model_name='asset',
            name='total_latent_demand_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='asset',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='fundamental_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='assetinvestors',
            name='latent_demand_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
    ]
