# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_demand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='company_name',
            field=models.CharField(default='1', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetinvestors',
            name='latent_demand_value',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='ticker',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='assetinvestors',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_investors', to='realtime_demand.Asset'),
        ),
        migrations.AlterField(
            model_name='assetinvestors',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_investors', to='realtime_demand.Investor'),
        ),
    ]
