# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_demand', '0003_auto_20170614_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetinvestors',
            name='stocks_owned',
            field=models.IntegerField(default=0),
        ),
    ]
